### PR TITLE
Galician translation

### PR DESCRIPTION
**Pull request by damufo**
Hi,
I send galician translation.
Thanks!

### CODE REVIEW

**Comment by olivierperez** [comment]
Hi, the Github project is a clone of the Gitlab one.
Can you send your work to https://git.framasoft.org/ please ?

By the way, you work seams almost good, you should add a value to `$ALLOWED_LANGUAGES` in `app/inc/config.template.php` in order to allow users to select Galician.

**Comment by damufo** [comment]
Hi Olivier,
Made!
Thank you!

Dani

**Comment by tcitworld** [comment]
@damufo You can also now translate at https://trad.framasoft.org.

**Comment by damufo** [comment]
Hello:
Y send you the galician translation 2 years ago.
I went to trad.framasoft.org but in framadate Galician does not appear to be able to send my translation.
captura de pantalla_2018-07-06_18-03-52

How can I send you the gl.json translated?
captura de pantalla_2018-07-06_18-03-52

**Comment by tcitworld** [comment]
We currently have a few issues with our translation process but I will import your file as soon as it's settled, you don't have to do anything. ;)

**Pull request closed without merging**
